package.json

follow up for https://github.com/octokit/rest.js/issues/824

don’t publish unnecessary files to npm

---

README.md

I noticed this browsing this project.
-----
[View rendered README.md](https://github.com/hjdarnel/endpoint.js/blob/master/README.md)

Fix typo in Readme- "endopint"

---

package.json

I don’t know what exactly increased the bundle size but it wasn’t endpoint.js code, and I don’t have the time to look into it now
closes #26

Bump max bundle size 3kb → 3.5kb

---

README.md
lib/defaults.js
lib/merge.js
lib/parse.js
test/defaults-test.js
test/endpoint-test.js
test/merge-test.js

closes #33
-----
[View rendered README.md](https://github.com/octokit/endpoint.js/blob/33/mediatype-parameter/README.md)

`options.mediaType.format` and `options.mediaType.previews`

---

tsconfig.json

This way the paths set for the `main` and `types` property in `package.json` exist and are not in a src subdirectory.
By enabling the `composite` flag, compile times will be faster and will only re-compile changed files, which will save time

build(typescript): Fix directory structure and enable project compiltion

---

package-lock.json
package.json
src/merge.ts
src/util/merge-deep.ts

I had problems cuased by deepmerge when trying to build browser bundles so I decided the simplest is to just remove it altogether and replace it with an implementation that only covers the cases we care about

Replace `deepmerge` dependency with own, simplified solution

---

src/merge.ts
test/merge.test.ts

This uses `Object.assign` to clone the `route` argument before assigning
it to the `options` variable.
Before this change a headers field was being set on the `options`
variable, which was the same reference. Another effect of this change is
that the headers field on the `route` argument would be mutated to be
lowercase. Now the lowercase operation happens on the cloned value
instead of mutating the argument passed in to the function.
Closes https://github.com/octokit/rest.js/issues/1394

fix(merge.ts): clone route argument to avoid mutation

---

README.md

Changes
- fixing table of content anchor links (several links were incorrect)
-----
[View rendered README.md](https://github.com/kevo1ution/endpoint.js/blob/Fix.Readme/README.md)

Fix Readme Table of Content Anchor Links

---

src/parse.ts
test/defaults.test.ts
test/endpoint.test.ts

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/endpoint.js/commit/5304f9b51533ea64c44f72576dcc1494344c1e06#commitcomment-41613540
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/endpoint.js/commit/693f49273848739f42334ca97f80620f9184ca10
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

refactor: spelling

---

src/parse.ts
test/endpoint.test.ts

Added test case and fix for #207

fix: encode URL parameters for :placeholder syntax

---

src/merge.ts
src/util/add-query-parameters.ts
src/util/remove-undefined-properties.ts
test/endpoint.test.ts

Fixes #206
I initially filtered out undefined query parameters in `add-query-parameters.ts`, but then I realized that undefined headers were also being erroneously included. To fix both of those I made it so that undefined values are removed from the options passed by the user before merging.

Filter out undefined query parameters and headers

---

.github/workflows/test.yml

Follow up to #326
Add a `test_matrix` step and then a `test` step that depends on `test_matrix`, so that for branch protections we can require `test` independent of the Node versions we are using.

ci(test): use `test_matrix` and `test` jobs

---

src/parse.ts
test/endpoint.test.ts

Currently, `DELETE` requests without a body don't work on the latest Node.js version, v18, because we try to set `content-length: 0` which is not allowed by the native `fetch` implementation which is included in Node. It throws an error with the `UND_ERR_REQ_CONTENT_LENGTH_MISMATCH` code.
This stops manually setting that `content-length: 0` header for `DELETE` requests.
I've tested this against the GitHub API with Node.js v18and v17, and both work as expected, with the GitHub API also accepting the request.
As part of this PR, I've also added some new tests covering what happens with different HTTP methods.
Fixes https://github.com/octokit/request.js/issues/506.

fix: fix support for Node.js v18's native `fetch` when making `DELETE` requests with no body

---

src/parse.ts

See #379, the tests are failing due to an error with typescript 
----
* The array was typed as `never[]`
* The array is now correctly types
* 
----
If `Yes`, what's the impact:  
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----

fix: type cast empty array to fix a typescript error

---

package-lock.json
package.json
scripts/build.mjs
src/defaults.ts
src/endpoint-with-defaults.ts
src/merge.ts
src/parse.ts
src/with-defaults.ts
test/parse.test.ts
test/tsconfig.test.json
tsconfig.json

Replicating [octokit/plugin-enterprise-server#571](https://github.com/octokit/plugin-enterprise-server.js/pull/571) to another repo. 
---
Pika has been deprecated for a while now, and the project has now been archived, and because of that the released npm package is missing most of the files generated by the build step.
Uses esbuild to transpile the TS source code into an ESM source, NodeJs bundle, and a browser bundle
Uses the TypeScript compiler to generate the types.
* Uses pika for the build system
* The released npm package is missing most of the files generated by the build step. `dist-node`, `dist-types`, `dist-web`... even though they are generated correctly.
* Uses esbuild to generate the JS bundles
* Uses the TypeScript compiler to generate the type definitions
* The correct …

fix(build): switch to esbuild instead of pika

---

src/merge.ts
test/endpoint.test.ts

Resolves #ISSUE_NUMBER
----
* Tests would fail in the beta version of `@octokit/graphql` because `mergedOptions.mediaType.previews` may be undefined
* If `mergedOptions.mediaType.previews` is undefined, use an empty array for the call to `Array#map()`
* Tests are now passing downstream with this fix
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
----

fix: account for possibility that `mergedOptions.mediaType.previews` may be undefined

---

src/util/url-template.ts
test/endpoint.test.ts

Resolves #395
----
* remove trailing slashes from URL except expanded endpoint is `/`
* if you specify url like `endpoint("https://github.acme-inc/api/v3/")`, it will cause to trailing slash removed.
* if you specify url like `endpoint("https://github.acme-inc/api/v3/")`, it will cause to trailing slash removed.
----

fix: remove trailing slash for invalid URL

---

src/util/omit.ts

This PR is improving the omit function performance by avoiding the array utility functions. It also initializes the object with __proto__: null to be more resilient to potential prototype pollutions. __proto__: null puts the object into dictionary mode which is slightly less performant. So probably the performance improvements of avoiding the array utility function is eaten by the dictionary mode. But I think the security aspect is more important. 
Resolves #ISSUE_NUMBER
----
* 
* 
----

fix(performance): improve omit

---

package-lock.json
package.json
src/defaults.ts
src/endpoint-with-defaults.ts
src/index.ts
src/merge.ts
src/parse.ts
src/util/merge-deep.ts
src/with-defaults.ts
test/defaults.test.ts
test/endpoint.test.ts
test/is-plaint-object.test.ts
test/merge.test.ts
test/parse.test.ts
test/tsconfig.test.json

This PR replaces NodeJS internal module imports with `node:` specifier imports.

refactor: use `node:` specifier imports and full relative import paths

---

README.md
scripts/build.mjs

Resolves octokit/core.js#667 
Resolves octokit/core.js#665
---
- Some consumers of this package could not resolve it properly (ex: `jest`, `ts-node`, `tsx`)
- CJS consumers would be getting errors even though the package is ESM
- Clients should be able to import the module without any errors with the fallback
- CJS consumers will generate a better error with the new fallback
---

 fix(pkg): add a default fallback export

---

package-lock.json
package.json

See https://github.com/octokit/octokit.js/issues/2762#issuecomment-2486997620
Resolves #ISSUE_NUMBER
----
* Types would include a reference to `@types/node` even though there is nothing using Node specific APIs in the types
* Update `@octokit/types` to make sure types are platform agnostic
----

fix(deps): bump `@octokit/types` to improve Deno compat

---

src/parse.ts
src/util/extract-url-variable-names.ts
test/parse.test.ts

backport of https://github.com/octokit/endpoint.js/releases/tag/v10.1.3

fix: ReDos regex vulnerability, reported by @DayShift

---

.github/workflows/update-prettier.yml
package.json

Resolves #ISSUE_NUMBER
----
* Outdated and un-used Jest config present in `package.json`
* Used Node 16 for the `update-prettier` workflow
* Removes the un-used Jest config
* Uses Node LTS instead of pinning to a specific version
----

maint: cleanup `package.json` and use Node LTS instead of v16
